services:

  backend:
    build: ./drf-react-todolist
    container_name: django-backend
    ports:
      - "8000:8000"

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./client
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend



